# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/Top_eq_core_0_0.xci
# IP: The module: 'Top_eq_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# IP: C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/Top_eq_core_0_0.xci
# IP: The module: 'Top_eq_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
