# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_xbar_0/Top_xbar_0.xci
# IP: The module: 'Top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_xbar_0/Top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_xbar_0/Top_xbar_0.xci
# IP: The module: 'Top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_xbar_0/Top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
