# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Zynq_Book/EQ_27/eq_27_zedboard.xdc

# Block Designs: bd/Top/Top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top || ORIG_REF_NAME==Top} -quiet] -quiet

# IP: bd/Top/ip/Top_eq_core_0_0/Top_eq_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_eq_core_0_0 || ORIG_REF_NAME==Top_eq_core_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_processing_system7_0_0/Top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_processing_system7_0_0 || ORIG_REF_NAME==Top_processing_system7_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_0_0/Top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_0_0 || ORIG_REF_NAME==Top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_i2s_receiver_0_0/Top_axi_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_axi_i2s_receiver_0_0 || ORIG_REF_NAME==Top_axi_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_i2s_transmitter_0_0/Top_axi_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_axi_i2s_transmitter_0_0 || ORIG_REF_NAME==Top_axi_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_axi_gpio_0_0 || ORIG_REF_NAME==Top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_rst_ps7_0_100M_0/Top_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_rst_ps7_0_100M_0 || ORIG_REF_NAME==Top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xbar_0/Top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_xbar_0 || ORIG_REF_NAME==Top_xbar_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_blk_mem_gen_0_1/Top_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_blk_mem_gen_0_1 || ORIG_REF_NAME==Top_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_ds_1/Top_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_ds_1 || ORIG_REF_NAME==Top_auto_ds_1} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_pc_1/Top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_pc_1 || ORIG_REF_NAME==Top_auto_pc_1} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_ds_0/Top_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_ds_0 || ORIG_REF_NAME==Top_auto_ds_0} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_pc_0/Top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_pc_0 || ORIG_REF_NAME==Top_auto_pc_0} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_pc_2/Top_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_pc_2 || ORIG_REF_NAME==Top_auto_pc_2} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_us_0/Top_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Top_auto_us_0 || ORIG_REF_NAME==Top_auto_us_0} -quiet] -quiet

# XDC: bd/Top/Top_ooc.xdc
