# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Zynq_Book/EQ_27/EQ_27.cache/wt [current_project]
set_property parent.project_path C:/Zynq_Book/EQ_27/EQ_27.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  c:/Zynq_Book/ip_repo/axi_i2s_receiver_1.0
  c:/Zynq_Book/ip_repo/axi_i2s_transmitter
  c:/Zynq_Book/ip_repo/eq_core
} [current_project]
set_property ip_output_repo c:/Zynq_Book/EQ_27/EQ_27.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/hdl/Top_wrapper.v
add_files C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/Top.bd
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_eq_core_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_processing_system7_0_0/Top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_rst_ps7_0_100M_0/Top_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_rst_ps7_0_100M_0/Top_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_rst_ps7_0_100M_0/Top_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_xbar_0/Top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_blk_mem_gen_0_1/Top_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_1/Top_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_1/Top_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_1/Top_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_pc_1/Top_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_0/Top_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_0/Top_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_ds_0/Top_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_pc_0/Top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_pc_2/Top_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_us_0/Top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_us_0/Top_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/ip/Top_auto_us_0/Top_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Zynq_Book/EQ_27/EQ_27.srcs/sources_1/bd/Top/Top_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Zynq_Book/EQ_27/eq_27_zedboard.xdc
set_property used_in_implementation false [get_files C:/Zynq_Book/EQ_27/eq_27_zedboard.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Top_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_wrapper_utilization_synth.rpt -pb Top_wrapper_utilization_synth.pb"
